### ISSUE TITLE
Change layout type

### ISSUE THREAD

**Issue by jarrodpayne** [czettnersandor/magento-quick-view-ajax#10]
First, I would like to say, this is a fantastic extension. I was able to integrate it in an extremely short amount of time. My problem comes with trying to modify your example, but a solution on this may help others in the future. Basically, I am trying to modify the `product.phtml` so it may contain a call to:

``` php
<?php echo $this->getChildHtml('media') ?>
```

Simply placing that block inside the product.phtml doesn't do anything, and I'm too confused on Magento's inner workings to figure out why. I could be way off base, but I do believe it has something to do with the fact that the `product.phtml` file is not a `catalog/product_view` block type or the fact that `media.phtml` is not listed as a child of the `product.phtml` file in some way. **Let me know if I'm just way off here**.

Here are a few snippets that I think should be useful. I just have no clue where to put them.

``` xml
<block type="catalog/product_view_media" name="product.info.media" as="media" template="catalog/product/view/media.phtml" />
```

``` xml
<block type="catalog/product_view" name="ajax.product" template="czettner_ajax/product.phtml" />
```

I'm thinking that it would be useful for these to be located somewhere in your czettner_ajax.xml file, but have no clue how they fit in the `<reference>` or `<catalog_category_layered>` type tags.

Any help would be greatly appreciated. Eventually, I will get the hang of the whole Magento layouts & blocks thing, but, for now, I'm just getting by.

**Comment by afsanamalik** [comment]
Hi czettnersandor. Its a wonderful extension. Thanks a lot, you saved my time and efforts. But have you implemented the configurable product options? I am really in need of it. Please share the code/extension immediately if possible. My Email ID - afsana.bargir@gmail.com. Thanks in advance. Looking forward..
