### ISSUE TITLE
Add products directly to cart

### ISSUE THREAD

**Issue by nimila** [czettnersandor/magento-quick-view-ajax#11]
Hi  czettnersandor,
How to implement add to cart directly to shopping cart page by providing options in the quick view pop up itself.
Thanks in advance.

**Comment by myhip** [comment]
HI, the same question for me. Can you give me some suggestions how to provide attribute options in the pop up page? Regards!

**Comment by savah** [comment]
Did you manage to implement this @czettnersandor ?

**Comment by czettnersandor** [comment]
No, sorry guys. I'm not planning any new implementation unless one of my clients need it now. Pull requests are welcomed, however.
