### ISSUE TITLE
Whats is the Callback function when using the infinite scrolling on the product listing pages?

### ISSUE THREAD

**Issue by ibrahimbm** [czettnersandor/magento-quick-view-ajax#13]
Whats is the Callback function when using the infinite scrolling on the product listing pages?

**Comment by czettnersandor** [comment]
This has been added to the specification of the new extension I'm working on. It should use a more sane javascript.

**Comment by Vivendo** [comment]
Hi I am getting same issue. I am using infinite scroll and quick view not working on next pages.
Can you suggest me best solution ?

**Comment by Vivendo** [comment]
Hi, 
I am getting same issue as mention above.I am using infinite scroll and quick view not working on next page.Please suggest me solution if you have.

**Comment by czettnersandor** [comment]
Have you tried the sample code two comments above: https://github.com/czettnersandor/magento-quick-view-ajax/issues/13#issuecomment-38833563

**Comment by Vivendo** [comment]
how we can store the ProductInfo object to a variable? Can you give me example?

**Comment by Stajon** [comment]
Hi,
I have the same problem. 
Unfortunately I am not experienced enough to use your solution. Could you help me with more information?
Where do I have to store productInfo Object?
Do I need a new function with mentioned code in the productInfo.js?
